export type Project = {
  id: number;
  title: string;
  category: string;
  location: string;
  year: string;
  client: string;
  shortDescription: string;
  fullDescription: string;
  images: string[];
  area: string;
  duration: string;
  status: string;
};

// English project data
export const projectsDataEn: Project[] = [
  {
    id: 1,
    title: 'Modern Residential Villa',
    category: 'Residential',
    location: 'Mumbai, Maharashtra',
    year: '2023',
    client: 'Private Client',
    shortDescription: 'A stunning contemporary villa featuring sustainable design principles and luxury living spaces...',
    fullDescription: 'This exceptional residential project showcases our commitment to sustainable luxury living. The villa features innovative architectural elements including solar panels, rainwater harvesting, and natural ventilation systems. The design seamlessly integrates indoor and outdoor spaces, creating a harmonious living environment that connects residents with nature while providing all modern amenities.',
    images: ['/assets/projects/modern-villa-1.jpg', '/assets/projects/modern-villa-2.jpg', '/assets/projects/modern-villa-3.jpg'],
    area: '4,500 sq ft',
    duration: '18 months',
    status: 'Completed',
  },
  {
    id: 2,
    title: 'Corporate Headquarters',
    category: 'Commercial',
    location: 'Pune, Maharashtra',
    year: '2023',
    client: 'Tech Solutions Pvt Ltd',
    shortDescription: 'A state-of-the-art corporate building designed for productivity and employee well-being...',
    fullDescription: 'This innovative corporate headquarters redefines modern workspace design. Featuring open collaborative spaces, private work pods, recreational areas, and advanced technology integration. The building incorporates green building principles with LEED certification, natural lighting, and energy-efficient systems that reduce operational costs while enhancing employee productivity and satisfaction.',
    images: ['/assets/projects/corporate-hq-1.jpg', '/assets/projects/corporate-hq-2.jpg', '/assets/projects/corporate-hq-3.jpg'],
    area: '50,000 sq ft',
    duration: '24 months',
    status: 'Completed',
  },
  {
    id: 3,
    title: 'Heritage Hotel Restoration',
    category: 'Hospitality',
    location: 'Jaipur, Rajasthan',
    year: '2022',
    client: 'Heritage Hotels Group',
    shortDescription: 'Careful restoration of a historic palace converted into a luxury boutique hotel...',
    fullDescription: 'This challenging restoration project involved converting a 200-year-old palace into a luxury boutique hotel while preserving its historical significance and architectural integrity. Our team worked closely with heritage conservation experts to restore original frescoes, intricate stone carvings, and traditional architectural elements while integrating modern hospitality amenities and safety systems.',
    images: ['/assets/projects/heritage-hotel-1.jpg', '/assets/projects/heritage-hotel-2.jpg', '/assets/projects/heritage-hotel-3.jpg'],
    area: '25,000 sq ft',
    duration: '30 months',
    status: 'Completed',
  },
  {
    id: 4,
    title: 'Educational Campus',
    category: 'Educational',
    location: 'Bangalore, Karnataka',
    year: '2023',
    client: 'Progressive Education Trust',
    shortDescription: 'A modern educational campus designed to foster learning and creativity...',
    fullDescription: 'This comprehensive educational campus project includes multiple academic buildings, laboratories, libraries, recreational facilities, and residential quarters. The design emphasizes creating inspiring learning environments with flexible classroom spaces, collaborative zones, and outdoor learning areas. Sustainable features include solar power generation, waste management systems, and water conservation measures.',
    images: ['/assets/projects/educational-campus-1.jpg', '/assets/projects/educational-campus-2.jpg', '/assets/projects/educational-campus-3.jpg'],
    area: '100,000 sq ft',
    duration: '36 months',
    status: 'Under Construction',
  },
  {
    id: 5,
    title: 'Luxury Apartment Complex',
    category: 'Residential',
    location: 'Delhi, NCR',
    year: '2022',
    client: 'Premium Living Developers',
    shortDescription: 'High-end apartment complex with premium amenities and modern design...',
    fullDescription: 'This luxury residential complex features 200 premium apartments across multiple towers with world-class amenities including swimming pools, fitness centers, landscaped gardens, and community spaces. The design emphasizes natural light, ventilation, and panoramic city views while incorporating smart home technologies and sustainable building practices for modern urban living.',
    images: ['/assets/projects/luxury-apartments-1.jpg', '/assets/projects/luxury-apartments-2.jpg', '/assets/projects/luxury-apartments-3.jpg'],
    area: '300,000 sq ft',
    duration: '42 months',
    status: 'Completed',
  },
  {
    id: 6,
    title: 'Medical Center Complex',
    category: 'Healthcare',
    location: 'Chennai, Tamil Nadu',
    year: '2023',
    client: 'HealthCare Solutions',
    shortDescription: 'State-of-the-art medical facility designed for patient comfort and operational efficiency...',
    fullDescription: 'This comprehensive medical center includes specialized treatment areas, diagnostic facilities, surgical suites, and patient recovery spaces. The design prioritizes patient comfort, privacy, and accessibility while ensuring efficient workflow for medical staff. Advanced HVAC systems, specialized lighting, and infection control measures create a safe and healing environment for patients and healthcare professionals.',
    images: ['/assets/projects/medical-center-1.jpg', '/assets/projects/medical-center-2.jpg', '/assets/projects/medical-center-3.jpg'],
    area: '75,000 sq ft',
    duration: '28 months',
    status: 'Completed',
  },
  {
    id: 7,
    title: 'Shopping Mall & Entertainment',
    category: 'Commercial',
    location: 'Hyderabad, Telangana',
    year: '2024',
    client: 'Retail Ventures Ltd',
    shortDescription: 'Modern shopping and entertainment complex with innovative retail spaces...',
    fullDescription: 'This dynamic shopping and entertainment complex combines retail spaces, restaurants, cinema, and recreational facilities under one roof. The design creates an engaging customer experience with natural lighting, comfortable circulation areas, and flexible retail spaces. Sustainable features include energy-efficient lighting, waste management systems, and green roof gardens that enhance the urban environment.',
    images: ['/assets/projects/shopping-mall-1.jpg', '/assets/projects/shopping-mall-2.jpg', '/assets/projects/shopping-mall-3.jpg'],
    area: '200,000 sq ft',
    duration: '48 months',
    status: 'Under Construction',
  },
  {
    id: 8,
    title: 'Sustainable Housing Project',
    category: 'Residential',
    location: 'Goa',
    year: '2024',
    client: 'Green Living Society',
    shortDescription: 'Eco-friendly housing development focused on sustainable living practices...',
    fullDescription: 'This innovative housing project demonstrates our commitment to environmental sustainability and community living. Features include passive solar design, rainwater harvesting, organic waste management, renewable energy systems, and community gardens. The development creates a self-sufficient eco-community that minimizes environmental impact while providing comfortable, affordable housing for families.',
    images: ['/assets/projects/sustainable-housing-1.jpg', '/assets/projects/sustainable-housing-2.jpg', '/assets/projects/sustainable-housing-3.jpg'],
    area: '150,000 sq ft',
    duration: '40 months',
    status: 'Planning',
  },
  {
    id: 9,
    title: 'Smart Office Tower',
    category: 'Commercial',
    location: 'Gurgaon, Haryana',
    year: '2024',
    client: 'Innovation Corp',
    shortDescription: 'Intelligent office building with IoT integration and smart building management systems...',
    fullDescription: 'This cutting-edge office tower incorporates the latest smart building technologies including automated climate control, intelligent lighting systems, and IoT sensors for optimal energy management. The building features flexible workspace configurations, collaborative zones, and advanced security systems. The design promotes productivity while reducing environmental impact through smart resource utilization.',
    images: ['/assets/projects/medical-center-2.jpg', '/assets/projects/sustainable-housing-1.jpg', '/assets/projects/corporate-hq-3.jpg'],
    area: '80,000 sq ft',
    duration: '32 months',
    status: 'Under Construction',
  },
  {
    id: 10,
    title: 'Boutique Hotel & Spa',
    category: 'Hospitality',
    location: 'Udaipur, Rajasthan',
    year: '2023',
    client: 'Royal Retreat Hotels',
    shortDescription: 'Luxury boutique hotel with world-class spa facilities and lake views...',
    fullDescription: 'This elegant boutique hotel offers an intimate luxury experience with panoramic views of Lake Pichola. The property features 25 uniquely designed rooms, a world-class spa with traditional Ayurvedic treatments, fine dining restaurants, and infinity pools. The design seamlessly blends traditional Rajasthani architecture with modern luxury amenities, creating an unforgettable guest experience.',
    images: ['/assets/projects/heritage-hotel-1.jpg', '/assets/projects/luxury-apartments-2.jpg', '/assets/projects/shopping-mall-3.jpg'],
    area: '35,000 sq ft',
    duration: '26 months',
    status: 'Completed',
  },
  {
    id: 11,
    title: 'Research & Development Center',
    category: 'Industrial',
    location: 'Bangalore, Karnataka',
    year: '2024',
    client: 'Tech Innovations Ltd',
    shortDescription: 'Advanced R&D facility with cutting-edge laboratories and innovation spaces...',
    fullDescription: 'This state-of-the-art R&D center houses advanced research laboratories, prototype development facilities, and collaborative innovation spaces. The facility includes specialized testing environments, clean rooms, and flexible research areas that can adapt to various technological requirements. The design prioritizes safety, efficiency, and collaboration while maintaining strict environmental controls.',
    images: ['/assets/projects/educational-campus-1.jpg', '/assets/projects/modern-villa-3.jpg', '/assets/projects/medical-center-1.jpg'],
    area: '120,000 sq ft',
    duration: '38 months',
    status: 'Under Construction',
  },
  {
    id: 12,
    title: 'Mixed-Use Development',
    category: 'Commercial',
    location: 'Mumbai, Maharashtra',
    year: '2024',
    client: 'Urban Development Corp',
    shortDescription: 'Integrated development combining retail, office, and residential spaces...',
    fullDescription: 'This comprehensive mixed-use development creates a self-contained urban community featuring retail spaces, office towers, residential apartments, and recreational facilities. The project includes pedestrian-friendly walkways, public plazas, and green spaces that enhance the urban experience. The design promotes walkability and reduces the need for vehicular transportation while creating a vibrant community hub.',
    images: ['/assets/projects/sustainable-housing-2.jpg', '/assets/projects/corporate-hq-1.jpg', '/assets/projects/heritage-hotel-3.jpg'],
    area: '500,000 sq ft',
    duration: '60 months',
    status: 'Planning',
  },
  {
    id: 13,
    title: 'Sports Complex & Stadium',
    category: 'Sports',
    location: 'Ahmedabad, Gujarat',
    year: '2023',
    client: 'Sports Authority of India',
    shortDescription: 'Multi-purpose sports facility with international standard amenities...',
    fullDescription: 'This world-class sports complex includes a main stadium with seating for 25,000 spectators, multiple training facilities, swimming pools, indoor courts, and fitness centers. The facility is designed to host international sporting events while serving as a training ground for athletes. Advanced lighting, sound systems, and broadcasting infrastructure ensure optimal conditions for both athletes and spectators.',
    images: ['/assets/projects/modern-villa-2.jpg', '/assets/projects/luxury-apartments-1.jpg', '/assets/projects/educational-campus-3.jpg'],
    area: '400,000 sq ft',
    duration: '44 months',
    status: 'Completed',
  },
  {
    id: 14,
    title: 'Cultural Center & Museum',
    category: 'Cultural',
    location: 'Kolkata, West Bengal',
    year: '2024',
    client: 'Ministry of Culture',
    shortDescription: 'Modern cultural center showcasing regional art, history, and performing arts...',
    fullDescription: 'This cultural center serves as a hub for artistic expression and cultural preservation. The facility includes exhibition galleries, performance theaters, art studios, and educational spaces. The design incorporates traditional Bengali architectural elements with modern museum standards, creating spaces that are both functional and inspiring. Climate-controlled galleries and advanced lighting systems ensure optimal conditions for art preservation.',
    images: ['/assets/projects/shopping-mall-1.jpg', '/assets/projects/heritage-hotel-2.jpg', '/assets/projects/corporate-hq-3.jpg'],
    area: '85,000 sq ft',
    duration: '34 months',
    status: 'Under Construction',
  },
  {
    id: 15,
    title: 'Data Center Campus',
    category: 'Technology',
    location: 'Pune, Maharashtra',
    year: '2024',
    client: 'Cloud Solutions Inc',
    shortDescription: 'High-security data center with redundant systems and green energy solutions...',
    fullDescription: 'This advanced data center campus features multiple server halls with redundant power systems, cooling infrastructure, and security measures. The facility incorporates green energy solutions including solar panels and energy-efficient cooling systems. The design prioritizes reliability, security, and environmental sustainability while maintaining optimal conditions for critical IT infrastructure.',
    images: ['/assets/projects/sustainable-housing-1.jpg', '/assets/projects/medical-center-2.jpg', '/assets/projects/modern-villa-3.jpg'],
    area: '200,000 sq ft',
    duration: '36 months',
    status: 'Under Construction',
  },
  {
    id: 16,
    title: 'Senior Living Community',
    category: 'Residential',
    location: 'Pune, Maharashtra',
    year: '2023',
    client: 'Golden Years Society',
    shortDescription: 'Comprehensive senior living community with healthcare and recreational facilities...',
    fullDescription: 'This thoughtfully designed senior living community provides independent living, assisted living, and memory care options. The facility includes healthcare clinics, recreational centers, dining facilities, and landscaped gardens. The design emphasizes accessibility, safety, and social interaction while creating a comfortable and dignified living environment for seniors.',
    images: ['/assets/projects/luxury-apartments-3.jpg', '/assets/projects/educational-campus-1.jpg', '/assets/projects/shopping-mall-2.jpg'],
    area: '180,000 sq ft',
    duration: '30 months',
    status: 'Completed',
  },
  {
    id: 17,
    title: 'Aviation Training Center',
    category: 'Educational',
    location: 'Hyderabad, Telangana',
    year: '2024',
    client: 'Aviation Academy',
    shortDescription: 'Comprehensive aviation training facility with simulators and classrooms...',
    fullDescription: 'This specialized training center includes flight simulators, classrooms, briefing rooms, and practical training areas. The facility is designed to provide comprehensive aviation education including pilot training, aircraft maintenance, and aviation management. Advanced simulation technology and realistic training environments ensure high-quality education and skill development.',
    images: ['/assets/projects/luxury-apartments-1.jpg', '/assets/projects/modern-villa-2.jpg', '/assets/projects/shopping-mall-1.jpg'],
    area: '95,000 sq ft',
    duration: '28 months',
    status: 'Under Construction',
  },
  {
    id: 18,
    title: 'Luxury Resort & Golf Course',
    category: 'Hospitality',
    location: 'Coorg, Karnataka',
    year: '2024',
    client: 'Nature Retreat Resorts',
    shortDescription: 'Premium resort with championship golf course and nature-inspired accommodations...',
    fullDescription: 'This luxury resort offers an immersive nature experience with premium accommodations, a championship golf course, spa facilities, and adventure activities. The design harmonizes with the natural landscape, featuring sustainable architecture and eco-friendly practices. The resort provides guests with both luxury amenities and authentic nature experiences in the beautiful Coorg region.',
    images: ['/assets/projects/educational-campus-2.jpg', '/assets/projects/corporate-hq-2.jpg', '/assets/projects/modern-villa-1.jpg'],
    area: '250,000 sq ft',
    duration: '48 months',
    status: 'Planning',
  },
  {
    id: 19,
    title: 'Innovation Hub & Startup Incubator',
    category: 'Commercial',
    location: 'Bangalore, Karnataka',
    year: '2024',
    client: 'Startup India',
    shortDescription: 'Dynamic workspace for startups with mentorship and networking facilities...',
    fullDescription: 'This innovation hub provides flexible workspaces, meeting rooms, and networking areas for startups and entrepreneurs. The facility includes mentorship spaces, pitch rooms, and collaborative zones designed to foster creativity and business growth. The design promotes interaction and collaboration while providing the infrastructure needed for successful business development.',
    images: ['/assets/projects/heritage-hotel-2.jpg', '/assets/projects/sustainable-housing-3.jpg', '/assets/projects/medical-center-3.jpg'],
    area: '65,000 sq ft',
    duration: '22 months',
    status: 'Under Construction',
  },
  {
    id: 20,
    title: 'Renewable Energy Plant',
    category: 'Industrial',
    location: 'Jaisalmer, Rajasthan',
    year: '2023',
    client: 'Green Energy Corp',
    shortDescription: 'Solar power plant with advanced energy storage and distribution systems...',
    fullDescription: 'This large-scale renewable energy facility generates clean electricity through solar panels and includes advanced energy storage systems. The plant features monitoring centers, maintenance facilities, and grid integration infrastructure. The design maximizes energy production while minimizing environmental impact, contributing to India\'s renewable energy goals.',
    images: ['/assets/projects/luxury-apartments-3.jpg', '/assets/projects/educational-campus-3.jpg', '/assets/projects/shopping-mall-2.jpg'],
    area: '1,000,000 sq ft',
    duration: '52 months',
    status: 'Completed',
  },
  {
    id: 21,
    title: 'Modern Library & Learning Center',
    category: 'Educational',
    location: 'Delhi, NCR',
    year: '2024',
    client: 'Delhi Public Library',
    shortDescription: 'Contemporary library with digital resources and collaborative learning spaces...',
    fullDescription: 'This modern library combines traditional book collections with digital resources and collaborative learning spaces. The facility includes reading rooms, digital labs, meeting spaces, and outdoor reading areas. The design creates an inspiring environment for learning and research while providing access to both physical and digital information resources.',
    images: ['/assets/projects/modern-villa-1.jpg', '/assets/projects/corporate-hq-1.jpg', '/assets/projects/heritage-hotel-1.jpg'],
    area: '75,000 sq ft',
    duration: '26 months',
    status: 'Under Construction',
  },
  {
    id: 22,
    title: 'Luxury Car Dealership & Service Center',
    category: 'Commercial',
    location: 'Mumbai, Maharashtra',
    year: '2024',
    client: 'Premium Motors',
    shortDescription: 'High-end automotive facility with showroom, service center, and customer lounge...',
    fullDescription: 'This premium automotive facility features an elegant showroom, state-of-the-art service center, and luxurious customer lounge. The design creates an exceptional customer experience with modern aesthetics, comfortable waiting areas, and transparent service bays. The facility combines functionality with luxury to provide a world-class automotive service experience.',
    images: ['/assets/projects/luxury-apartments-2.jpg', '/assets/projects/medical-center-1.jpg', '/assets/projects/sustainable-housing-1.jpg'],
    area: '45,000 sq ft',
    duration: '20 months',
    status: 'Under Construction',
  },
  {
    id: 23,
    title: 'Wellness Center & Spa Resort',
    category: 'Hospitality',
    location: 'Rishikesh, Uttarakhand',
    year: '2024',
    client: 'Wellness Retreats',
    shortDescription: 'Holistic wellness center offering yoga, meditation, and therapeutic treatments...',
    fullDescription: 'This wellness center provides a comprehensive approach to health and well-being with yoga studios, meditation halls, therapeutic treatment rooms, and accommodation facilities. The design creates a serene environment that promotes relaxation and healing, incorporating natural materials and peaceful spaces that connect guests with the spiritual atmosphere of Rishikesh.',
    images: ['/assets/projects/modern-villa-3.jpg', '/assets/projects/corporate-hq-2.jpg', '/assets/projects/educational-campus-1.jpg'],
    area: '60,000 sq ft',
    duration: '24 months',
    status: 'Planning',
  },
  {
    id: 24,
    title: 'Smart City Command Center',
    category: 'Technology',
    location: 'Surat, Gujarat',
    year: '2024',
    client: 'Surat Municipal Corporation',
    shortDescription: 'Integrated command center for smart city operations and emergency response...',
    fullDescription: 'This advanced command center serves as the nerve center for smart city operations, integrating traffic management, emergency response, utility monitoring, and public services. The facility features advanced technology systems, data visualization centers, and emergency response coordination areas. The design ensures efficient city management and rapid response to urban challenges.',
    images: ['/assets/projects/heritage-hotel-3.jpg', '/assets/projects/sustainable-housing-2.jpg', '/assets/projects/medical-center-2.jpg'],
    area: '55,000 sq ft',
    duration: '18 months',
    status: 'Under Construction',
  },
];
